# Generated by Django 2.0.7 on 2018-07-18 06:45

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180718_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='test', verbose_name='文章'),
        ),
    ]
